version: "3.9"

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"         # Edge endpoint for all services (S3 included)
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=s3
      - DEBUG=0
      - AWS_DEFAULT_REGION=us-east-1
      # Persist data between restarts (optional, but nice when iterating)
      - LS_DATA_DIR=/var/lib/localstack/data
    volumes:
      - "./.localstack:/var/lib/localstack"
