import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import GlobalLoading from "@/components/ui/global-loading";
import { Suspense } from "react";
import { getCspNonce } from "@/lib/security/get-csp-nonce";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const nonce = await getCspNonce();

  return (
    <html
      lang="en"
      className="light"
      style={{ colorScheme: "light" }}
      suppressHydrationWarning
    >
      <head>
        {/* Surface the request nonce to client components that need it */}
        <meta name="csp-nonce" content={nonce ?? ""} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Suspense fallback={<div className="text-sm text-muted-foreground">Loading…</div>}>
          <GlobalLoading />
          {children}
        </Suspense>
      </body>
    </html>
  );
}
